# Generated by Django 4.1.7 on 2023-02-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_name',
            new_name='role',
        ),
    ]
